version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
        - "*"

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/src"
    target-branch: "main"
    schedule:
      interval: "daily"
    groups:
      minor-patch:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
