blank_issues_enabled: false
contact_links:
  - name: aliae Docs
    url: https://aliae.dev/docs
    about: RTFM
  - name: aliae Q&A
    url: https://github.com/JanDeDobbeleer/aliae/discussions
    about: Please ask questions here.
