name: Bluesky
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bluesky:
    uses: jandedobbeleer/workflows/.github/workflows/bluesky.yml@main
    with:
      identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
      password: ${{ secrets.BLUESKY_PASSWORD }}
      token: ${{ secrets.GH_PAT }}
      title: "Something is sprouting 🌱"

