name: Contributors
on:
  pull_request_target:
    types:
      - closed

jobs:
  contributors:
    uses: jandedobbeleer/workflows/.github/workflows/contributors.yml@main
    with:
      token: ${{ secrets.GH_PAT }}
